# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = ["acpi_rev_override=1" "pcie_aspm=off"];
  boot.extraModprobeConfig = "install nouveau /run/current-system/sw/bin/false";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8f32a568-5c9a-46c9-bd85-3869d60f6d4b";
      fsType = "ext4";
    };

  # boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/c3894b66-f79c-465f-b11e-32b78035fa46";
  boot.initrd.luks.devices =
  [
    {
      name = "root";
      device = "/dev/disk/by-uuid/c3894b66-f79c-465f-b11e-32b78035fa46";
      keyFile = "/dev/disk/by-id/usb-SanDisk_Cruzer_Switch_4C532000061005117093-0:0";
      keyFileSize = 256;
      allowDiscards = true;
      fallbackToPassword = true;
    }
  ];
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9D78-C770";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6eb307fd-9aff-4e63-9853-01dd700120d8"; }
    ];

  # Keep me updated
  services.fwupd.enable = true;
  hardware.cpu.intel.updateMicrocode = true;

  # Enable periodic SSD TRIM (default weekly)
  services.fstrim.enable = true;

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
