{
  networking.proxy =
  let
    # proxy = "http://127.0.0.1:3128";
    proxy = "http://193.56.47.8:8080";
  in
  {
    httpProxy = proxy;
    httpsProxy = proxy;
    noProxy = "127.0.0.1,localhost,::1";
  };  ## Networking configuration

  #services.polipo.enable = true;
  #services.polipo.parentProxy = "193.56.47.8:8080";
  services.cntlm = {
    enable = false;
    username = "a606307";
    domain = "ww930";
    extraConfig = ''
    Auth				NTLMv2
    PassLM          76BAF3731308DBFA888D07AC2993FC0B
    PassNT          43589DDA66EF8CEA7C8CE1B86BDBEDDD
    PassNTLMv2      BFB7D679325849C5675150203FD9A0ED    # Only for user 'a606307', domain 'ww930'


    NoProxy	localhost
    NoProxy	127.0.0.*
    NoProxy	10.*
    NoProxy	192.168.*
    NoProxy	172.16.*
    NoProxy	*.sdmc.ao-srv.com
    NoProxy	intranet.adp.cio.siemens.de
    NoProxy	r3s.sbs.de
    NoProxy	marketdata.sfs.siemens.de
    NoProxy	workspace-search.siemens.com
    NoProxy	sap01015.os.fth.sbs.de
    NoProxy	sap01014.os.fth.sbs.de
    NoProxy	ix3pdms.ww004.siemens.net
    NoProxy	pkgph10d.eps.siemens.com
    NoProxy	ors.its.sbs.de
    NoProxy	sap08053.os.fth.sbs.de
    NoProxy	ixostamc.os.fth.sbs.de
    NoProxy	sap08051.os.fth.sbs.de
    NoProxy	ixospamc.os.fth.sbs.de
    NoProxy	sap08043.os.fth.sbs.de
    NoProxy	m05.eps.siemens.com
    NoProxy	cpqs.eps.siemens.com
    NoProxy	penlo-med.eps.siemens.com
    NoProxy	workspace.automation.siemens.com
    NoProxy	erlh11ka.ww005.siemens.net
    NoProxy	access.siemens.com.au
    NoProxy	acdc.erlm.siemens.de
    NoProxy	administration.dc4ca.siemens.de
    NoProxy	admin.pkisupport.siemens.com
    NoProxy	ads.siemens.com
    NoProxy	aumelbw20msx.au001.siemens.net
    NoProxy	azm.neut.siemens.at
    NoProxy	azur.sbs.de
    NoProxy	cmd.siemens.com
    NoProxy	corina.siemens.com
    NoProxy	cpo.erlm.siemens.de
    NoProxy	cpo-staging.erlm.siemens.de
    NoProxy	cpps.eps.siemens.com
    NoProxy	crsp2.siemens.com
    NoProxy	crsp-portal-malvern.siemens.com
    NoProxy	crsp-release.siemens.com
    NoProxy	crsp-reporting.siemens.com
    NoProxy	cti-dlf.siemens.de
    NoProxy	cti-erl.siemens.de
    NoProxy	cti.siemens.de
    NoProxy	deerls7eaa.ww007.siemens.net
    NoProxy	deerls7eba.ww007.siemens.net
    NoProxy	demchdc35tx.dc4ca.siemens.de
    NoProxy	dkbdkb7ema.ww007.siemens.net
    NoProxy	dkbdkb7ena.ww007.siemens.net
    NoProxy	ebasm1.siemens.com
    NoProxy	email.siemens.net
    NoProxy	flake.erlm.siemens.de
    NoProxy	flexsm.erlm.siemens.de
    NoProxy	hes-mgmt.pkisupport.siemens.com
    NoProxy	home.siemens-pse.sk
    NoProxy	ilbseh7eaa.ww007.siemens.net
    NoProxy	intranet.cee.siemens.com
    NoProxy	intranet.energy-ots.siemens.co.in
    NoProxy	intranet.macs.siemens.co.in
    NoProxy	intranet.nwe.siemens.com
    NoProxy	intranet.smw-test.cc.siemens.com
    NoProxy	intranet.ueasy.siemens.co.th
    NoProxy	i-web.it-solutions.myatos.net
    NoProxy	kzalad1p003msx.kz001.siemens.net
    NoProxy	lantree.erlm.siemens.de
    NoProxy	mosaic53.erlm.siemens.de
    NoProxy	oracleadm2.erlm.siemens.de
    NoProxy	owa.siemens.net
    NoProxy	rum.erlm.siemens.de
    NoProxy	saldojobs2.sbs.siemens.de
    NoProxy	scdwebgid.siemens.net
    NoProxy	sso.cpo.erlm.siemens.de
    NoProxy	sso.cpo-staging.erlm.siemens.de
    NoProxy	svn.erlm.siemens.de
    NoProxy	ttp.cit.siemens.de
    NoProxy	webmail.pg.siemens.com
    NoProxy	webmail.siemens.net
    NoProxy	wiki.healthcare.siemens.com
    NoProxy	workplace.siemens.net
    NoProxy	workspace.siemens.co.in
    NoProxy	wsol.erlm.siemens.de
    NoProxy	xsp.erlm.siemens.de
    NoProxy	esp.it-solutions.atos.net
    NoProxy	esp.siemens.com
    NoProxy	qc.cit.siemens.com
    NoProxy	senes.siemens.com
    NoProxy	cat.uma.sbs.de
    NoProxy	catsntravel-amcnwe.siemens.com
    NoProxy	ees.mch.sbs.de
    NoProxy	webapps.ct.siemens.de
    NoProxy	defthw99wassrv.ww004.siemens.net
    NoProxy	epm-service.siemens.com
    NoProxy	citrix.sml.siemens.co.uk
    NoProxy	frodo.siemens.de
    NoProxy	cms1.rd.siemens.com
    NoProxy	cps.siemens.com
    NoProxy	erlm5cca.erlm.siemens.de
    NoProxy	extranet-dev.siemens.com
    NoProxy	intra.siemens.nl
    NoProxy	intranet.siemens.co.uk
    NoProxy	sap01012.os.fth.sbs.de
    NoProxy	sap01304.eps.siemens.com
    NoProxy	scdlogin.siemens.net
    NoProxy	workspace.nwe.siemens.com
    NoProxy	workspace.siemens.co.uk
    NoProxy	entitlement.siemens.net
    NoProxy	lte-test.erlm.siemens.de
    NoProxy	entitlement.siemens.de
    NoProxy	intranet.saf.siemens.com
    NoProxy	workspace.ct.siemens.com
    NoProxy	intranet.gpportal.it-solutions.siemens.com
    NoProxy	chs.ww005.siemens.net
    NoProxy	intranet.swe.siemens.com
    NoProxy	intranet.ps.siemens.de
    NoProxy	eic.siemens.com
    NoProxy	shrs.siemens.com
    NoProxy	intranet.gss.siemens.com
    NoProxy	training.siemens.com
    NoProxy	intranet.domain-names.siemens.com
    NoProxy	demchdc36xa.ww500.siemens.net
    NoProxy	demchdc37ra.ww006.siemens.net
    NoProxy	intranet.ger.siemens.de
    NoProxy	mhpa4fgc.mch.sbs.de
    NoProxy	mhpa4f2c.mch.sbs.de
    NoProxy	mhpa4ehc.mch.sbs.de
    NoProxy	mchp7kia.ww002.siemens.net
    NoProxy	fthw9kka.ww002.siemens.net
    NoProxy	aperture.siemens.it
    NoProxy	apex.cio.siemens.de
    NoProxy	atnets197a.ww300.siemens.net
    NoProxy	atvies23ya.ww300.siemens.net
    NoProxy	atvies29sql02.ww300.siemens.net
    NoProxy	atvies9910rsrv.ww300.siemens.net
    NoProxy	aunz.siemens.com.au
    NoProxy	intranet.sfs.siemens.com
    NoProxy	intranet.siemens.ru
    NoProxy	livelink.siemens.ru
    NoProxy	pct.sfs.siemens.de
    NoProxy	rumowd10003web.ww600.siemens.net
    NoProxy	rumowd10119msx.ww600.siemens.net
    NoProxy	rumowk10235dat.ww600.siemens.net
    NoProxy	rumowl10029srv.ww600.siemens.net
    NoProxy	rumowmc0166srv.ww600.siemens.net
    NoProxy	rumowmc0905msx.ww600.siemens.net
    NoProxy	sp-01.erlm.siemens.de
    NoProxy	teamweb.industry.siemens.com
    NoProxy	ttp.sfs.siemens.de
    NoProxy	workspace-q.sfs.siemens.com
    NoProxy	workspace-q.ww300.siemens.net
    NoProxy	workspace.sfs.siemens.com
    NoProxy	intranet.editorswww.siemens.com
    NoProxy	esp-siemens.it-solutions.atos.net
    NoProxy	e-apps.ito.siemens.com
    NoProxy	hcp-ci.sie.siemens.at
    NoProxy	share-emea.med.siemens.de
    NoProxy	share-apac.med.siemens.de
    NoProxy	*-share.healthcare.siemens.com
    NoProxy	*.smshsc.net
    NoProxy	etd-jwp.eps.siemens.com
    NoProxy	moss.healthcare.siemens.com
    NoProxy	sharepoint.siemens.com
    NoProxy	gama.erlm.siemens.de
    NoProxy	portal.medical.siemens.com
    NoProxy	pkgbsp0d.os.fth.sbs.de
    NoProxy	cobp.automation.siemens.com
    NoProxy	cobauth.ww004.siemens.net
    NoProxy	medpoolp41.os.fth.sbs.de
    NoProxy	medpooli41.os.fth.sbs.de
    NoProxy	sap.med.siemens.de
    NoProxy	saperion.erlm.siemens.de
    NoProxy	workflow.sfs.siemens.com
    NoProxy	esmadt19002sql.ww002.siemens.net
    NoProxy	esmadt19003sql.ww002.siemens.net
    NoProxy	castor.myatos.net
    NoProxy	gdesk.myatos.net
    NoProxy	clarityforecasting.myatos.net
    NoProxy	*.int.atosorigin.com
    NoProxy	*.ao-srv.com
    NoProxy	scman.mch.myatos.net
    NoProxy	ict.siemens.com
    NoProxy	ict-qa.siemens.com
    NoProxy	hrs-ibi.siemens.net
    NoProxy	pct.cio.siemens.de
    NoProxy	hrsdirx.siemens.com
    NoProxy	bpc.myatos.net
    NoProxy	bpcdev.myatos.net
    NoProxy	bpctest.myatos.net
    NoProxy	bpcsandbox.myatos.net
    NoProxy	accountmanagement.siemens.com
    NoProxy	ix3qdms.ww004.siemens.net
    NoProxy	demchdc30pa.ww500.siemens.net
    NoProxy	nets146a-1.ww300.siemens.net
    NoProxy	smt.energy.siemens.com
    NoProxy	smt-test.energy.siemens.com
    NoProxy	*.nsn-intra.net
    NoProxy	*.nsn-net.net
    NoProxy	*.inside.nokiasiemensnetworks.com
    NoProxy	atvies9912ssrv.ww300.siemens.net
    NoProxy	simeacms.siemens.at
    NoProxy	defthw99w2aweb.ww002.siemens.net
    NoProxy	139.25.231.70
    NoProxy	139.25.233.58
    NoProxy	139.25.233.59
    NoProxy	139.25.234.103
    NoProxy	139.25.237.110
    NoProxy	139.25.240.13
    NoProxy	139.25.240.134
    NoProxy	139.25.240.15
    NoProxy	click4xpress-test.cit.siemens.com
    NoProxy	click4xpress.siemens.com
    NoProxy	demchdc049xsrv.dc4ca.siemens.de
    NoProxy	demchlb110x.lb4ca.siemens.de
    NoProxy	freia-test.cit.siemens.com
    NoProxy	ict.siemens.net
    NoProxy	www.freia.siemens.de
    NoProxy	webmail-emea.siemens.net
    NoProxy	194.8.116.87
    NoProxy	194.8.116.68
    NoProxy	194.8.118.99
    NoProxy	abctest2.eplus.de
    NoProxy	194.8.118.116
    NoProxy	intra.industry.siemens.com
    NoProxy	intranet.sbt.siemens.com
    NoProxy	soc.siemens.net
    NoProxy	intranet.w1.siemens.com
    NoProxy	194.8.112.23
    NoProxy	hpqc1.siemens.de
    NoProxy	hpqc2.siemens.de
    NoProxy	bdp-svn.siemens.com
    NoProxy	194.8.118.32
    NoProxy	pwblb100.ds.server.dom
    NoProxy	dwbaps60.ds.server.dom
    NoProxy	194.8.116.14
    NoProxy	jira.bdc-services.net
    NoProxy	hrsdirx-dev.siemens.com
    NoProxy	hrsdirx-test.siemens.com
    NoProxy	194.8.112.12
    NoProxy	194.8.112.18
    NoProxy	nsnrmt-web.access.nokiasiemensnetworks.com
    NoProxy	inside.nokiasiemensnetworks.com
    NoProxy	194.8.112.25
    NoProxy	sap01108.os.fth.sbs.de
    NoProxy	ict-dev.siemens.com
    NoProxy	194.8.116.82
    NoProxy	194.8.118.95
    NoProxy	extranet.volkswagen.com.br
    NoProxy	194.8.105.241
    NoProxy	194.174.147.196
    NoProxy	sap01106.os.fth.sbs.de
    NoProxy	sap01109.os.fth.sbs.de
    NoProxy	sap01236.os.fth.sbs.de
    NoProxy	cnpek01283.cn001.siemens.net
    NoProxy	194.8.120.177
    NoProxy	194.8.120.178
    NoProxy	sap01237.os.fth.sbs.de
    NoProxy	sap01238.os.fth.sbs.de
    NoProxy	sap01107.os.fth.sbs.de
    NoProxy	inside.nsn.com
    NoProxy	*.inside.nsn.com
    NoProxy	uratest-eu.it-solutions.atos.net
    NoProxy	ura-eu.it-solutions.atos.net
    NoProxy	ura-fr.it-solutions.atos.net
    NoProxy	ura-latam.it-solutions.atos.net
    NoProxy	ura-in.it-solutions.atos.net
    NoProxy	nw1.cf.siemens.de
    NoProxy	nw2.cf.siemens.de
    NoProxy	nw3.cf.siemens.de
    NoProxy	portal-login-dev.cf.siemens.de
    NoProxy	portal-login-prod.cf.siemens.de
    NoProxy	*.atos-infogerance.fr
    NoProxy	55.12.2.12
    NoProxy	nsnrmt-web.access.nsn.com
    NoProxy	idprove.myatos.net
    NoProxy	idprovestg.myatos.net
    NoProxy	mirrorstg.myatos.net
    NoProxy	misaplicaciones.es.myatos.net
    NoProxy	*.fr.myatos.net
    NoProxy	*.ftgroup
    NoProxy	citrix-sif-dev.aviation-civile.gouv.fr
    NoProxy	csg.aviation-civile.gouv.fr
    NoProxy	am7450.fr.int.atosorigin.com
    NoProxy	195.220.*
    NoProxy	193.56.241.157
    NoProxy	156.150.236.*
    NoProxy	cerbere.airbus.com
    NoProxy	arex-fr.airbus.com
    NoProxy	*.atosfusion.fr
    NoProxy	*.toulouse.it.atosorigin.com
    NoProxy	*.airbus.it.atosorigin.com
    NoProxy	*.ft.it.atosorigin.com
    NoProxy	*.francetelecom.fr
    NoProxy	*.airbus.corp
    NoProxy	*.airbus-v.corp
    NoProxy	*.dsna-dti.aviation
    NoProxy	55.1.39.126
    NoProxy	*.lyon.si.fr.atosorigin.com
    NoProxy	*.adc.sitree.net
    NoProxy	finance.siemens.ru
    NoProxy	workspaceqa-secure.sfs.siemens.com
    NoProxy	applicationsqa-secure.sfs.siemens.com
    NoProxy	workspace-secure.sfs.siemens.com
    NoProxy	applications-secure.sfs.siemens.com
    NoProxy	workspacedev-secure.sfs.siemens.com
    NoProxy	fs-auth.siemens.com
    NoProxy	sap01322.os.fth.sbs.de
    NoProxy	*.mvs.sitree.net
    NoProxy	*.airbus.it.atos.net
    NoProxy	*.dmz.it.atos.net
    NoProxy	*.dmz.it.atosorigin.com
    NoProxy	*.ft.it.atos.net
    NoProxy	*.dsna.aviation
    NoProxy	*.cnqd.cnamts.fr
    NoProxy	crsp1.siemens.com
    NoProxy	dei10sigsrv.ww005.siemens.net
    NoProxy	moss-us.healthcare.siemens.com
    NoProxy	reporting.med.siemens.com
    NoProxy	atvies26sx.sie.siemens.at
    NoProxy	atvies26rx.sie.siemens.at
    NoProxy	webmail-na.siemens.net
    NoProxy	webmail-cee.siemens.net
    NoProxy	*.grenoble.si.fr.atosorigin.com
    NoProxy	application.siemens.com
    NoProxy	*.kiloutou.ent.root
    NoProxy	aom.bdc-services.net
    NoProxy	e2j.siemens.com
    NoProxy	edi-betrieb.siemens.de
    NoProxy	remote.glasgow2014.com
    NoProxy	md17gp1c.ww002.siemens.net
    NoProxy	*.apac.myatos.net
    NoProxy	www.cert.siemens.com
    NoProxy	amc2.siemens.com
    NoProxy	sap01326.os.fth.sbs.de
    NoProxy	sap01327.os.fth.sbs.de
    NoProxy	sap03767.os.fth.sbs.de
    NoProxy	gate-fr.airbus.com
    NoProxy	xaas.fi.atos.net
    NoProxy	xaas-auth.fi.atos.net
    NoProxy	xaas-mgr.fi.atos.net
    NoProxy	xaas-web.fi.atos.net
    NoProxy	vcd01.fi.atos.net
    NoProxy	vcd01-con.fi.atos.net
    NoProxy	*.int.net.nokia.com
    NoProxy	hfm.bull.net
    NoProxy	oasis-v3.bull.net
    NoProxy	crm.ad.bull.net
    NoProxy	intranet.icmms.siemens.com
    NoProxy	cj01.erlm.siemens.de
    NoProxy	146.254.235.13
    NoProxy	*.ccpdev.net
    NoProxy	146.254.235.15
    NoProxy	146.254.235.18
    NoProxy	crsp-dw.siemens.com
    NoProxy	ccpdev.net
    NoProxy	pki.rs.entitlement.siemens.com
    NoProxy	cnpek01284.cn001.siemens.net
    NoProxy	hanvisning.se.atos.net
    NoProxy	workspace.c7.siemens.com
    NoProxy	lyncdiscoverinternal.atos.net
    NoProxy	esmadt19091sql.ww002.siemens.net
    NoProxy	esmadt19092sql.ww002.siemens.net
    NoProxy	cnpek01285.cn001.siemens.net
    NoProxy	qc-hit01.healthcare.siemens.com
    NoProxy	nacsg01.na.jnj.com
    NoProxy	emeacsg01.eu.jnj.com
    NoProxy	nacsg02.na.jnj.com
    NoProxy	emeacsg02.eu.jnj.com
    NoProxy	138.69.215.206
    NoProxy	cio.siemens.com
    NoProxy	netmri-ito.atos-nao.net
    NoProxy	fratf.fr.atos.net
    NoProxy	*.fratf.fr.atos.net
    NoProxy	138.69.246.109
    NoProxy	sitescandr.ito-na.atos.net
    NoProxy	sitescan.ito-na.atos.net
    NoProxy	aiqair.acs-inc.com
    NoProxy	accessa.aetna.com
    NoProxy	basadmin.corp.xerox.com
    NoProxy	basadmin10.corp.xerox.com
    NoProxy	acsreports.acs-inc.com
    NoProxy	13.129.59.160
    NoProxy	a1dal1swputil02.americas.oneacs.com
    NoProxy	acsdalrsa-pri.net.acs-inc.com
    NoProxy	acsdem23.acs-inc.com
    NoProxy	emmadmin.corp.xerox.com
    NoProxy	lockout.corp.xerox.com
    NoProxy	xww.s3.world.xerox.com
    NoProxy	acsdem23.acs-inc.com
    NoProxy	acsdem26.acs-inc.com
    NoProxy	acspem70.acs-inc.com
    NoProxy	noc.ecc.acsonline.com
    NoProxy	sevone-ito.atos-nao.net
    NoProxy	sevone-xim.atos-nao.net
    NoProxy	usa0300vm852.na.xerox.net
    NoProxy	*.my-it-solutions.net
    NoProxy	my-it-solutions.net
    NoProxy	*.plbyd.pl.int
    NoProxy	plbyd.pl.int
    NoProxy	*.ansiview.net
    NoProxy	ansiview.net
    NoProxy	*.adminarea.net
    NoProxy	adminarea.net
    NoProxy	*.sinius.org
    NoProxy	sinius.org
    NoProxy	*.sinius.de
    NoProxy	sinius.de
    NoProxy	*.sinius.com
    NoProxy	sinius.com
    NoProxy	*.sbi-ruhr.net
    NoProxy	sbi-ruhr.net
    NoProxy	*.ads0001.de
    NoProxy	ads0001.de
    NoProxy	*.siemens-it-solutions.com
    NoProxy	siemens-it-solutions.com
    NoProxy	*.siemens-it-solutions.de
    NoProxy	siemens-it-solutions.de
    NoProxy	*.salesservice.myatos.net
    NoProxy	salesservice.myatos.net
    NoProxy	*.it-solutions.myatos.net
    NoProxy	it-solutions.myatos.net
    NoProxy	*.it-dienstleistung.myatos.net
    NoProxy	it-dienstleistung.myatos.net
    NoProxy	*.aosrm.atosorigin.com
    NoProxy	aosrm.atosorigin.com
    NoProxy	*.atos-srv.net
    NoProxy	atos-srv.net
    NoProxy	*.access.it-solutions.atos.net
    NoProxy	access.it-solutions.atos.net
    NoProxy	*.fit.ch001.ch
    NoProxy	fit.ch001.ch
    NoProxy	172.16.*
    NoProxy	172.17.*
    NoProxy	172.18.*
    NoProxy	172.19.*
    NoProxy	172.20.*
    NoProxy	172.21.*
    NoProxy	172.22.*
    NoProxy	172.23.*
    NoProxy	172.24.*
    NoProxy	172.25.*
    NoProxy	172.26.*
    NoProxy	172.27.*
    NoProxy	172.28.*
    NoProxy	172.29.*
    NoProxy	172.30.*
    NoProxy	172.31.*
    NoProxy	192.168.*
    NoProxy	100.70.*
    NoProxy	100.74.*
    NoProxy	100.75.*
    NoProxy	160.92.255.*
    NoProxy	160.92.243.*
    NoProxy	160.92.246.*
    NoProxy	161.89.64.*
    NoProxy	160.92.235.*
    NoProxy	161.89.65.*
    '' ;
    proxy = [
      "proxy-fr.glb.my-it-solutions.net:84"
      "proxy-de.glb.my-it-solutions.net:84"
    ];
  };
}
